### ISSUE TITLE
The package_data isn't quite working right

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/event-model#1]
Any help, @tacaswell?

**Comment by ericdill** [comment]
Can you have package data with a single module package?

**Comment by danielballan** [comment]
That is exactly the right question, I think. I suspect the answer is no, but I couldn't find a definitive, documented answer.

**Comment by tacaswell** [comment]
Independent if you _can_ I do not think you _should_ as it would end up dumping a folder into the top level of your python installation with your data which is impolite.

**Comment by danielballan** [comment]
I made `event_model` a package and got everything working right. This now works with bluesky, and a conda package is uploaded to my channel. @ericdill you may want to package this on lightsource2 as well at some point.

**Comment by ericdill** [comment]
Could you push the conda recipe to master on https://github.com/nsls-ii/staged-recipes
