### ISSUE TITLE
Forbid forward slash in names.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/event-model#11]
Rationale: Data keys with forward slashes would make exporting to HDF5 files difficult. As far as we know no user has actually tried to violate this constraint, but it seems worth putting it into the specification defensively. We already forbid dots so this should be a simple change. Can you tackle this, @licode?

**Comment by licode** [comment]
OK, I will check this.

**Comment by danielballan** [comment]
Closed by #12.
