### ISSUE TITLE
Update docs to include new documents

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/event-model#16]
Would it be possible to update https://nsls-ii.github.io/architecture-overview.html to include the resource and datum documents?

**Comment by tacaswell** [comment]
In terms of clarity, I am not sure adding Resouce/Datum to that page would be an improvement.

**Comment by CJ-Wright** [comment]
Is there a page which contains an example of the Resource/Datum documents?

**Comment by tacaswell** [comment]
https://nsls-ii.github.io/databroker/assets.html

**Comment by CJ-Wright** [comment]
Thank you very much!
