### ISSUE TITLE
Add 'dims' to data_key

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/event-model#26]
## Proposal

Add an optional `dims` property to [the definition of `data_key`](https://github.com/NSLS-II/event-model/blob/777e0008bf48b0676e1f043e1c5d7db99657d492/event_model/schemas/event_descriptor.json#L6-L34) in Event Descriptors. The value of `dims` should be an `array` where each item is a `string`. For a very relevant example of how to specify this in jsonschema, see `shape` in the linked section of code.

## Motivation

Numpy arrays have a `shape` with N entries corresponding to `ndim` the number of dimensions in the array. Event Descriptors have a corresponding `shape` property, declaring the `shape` of the data in some field of an Event.

Xarrays add string labels to the array axes, called `dims` ("dimensions"). It would be good if ophyd Devices that return array day could suggest names for the dimensions, like `dims=('exposure', 'y', 'x')` for AreaDetector. It would would natural to put this in the `data_key` next to `shape`.

Then databroker can use this information to label the `dims` in an xarray correspondingly and make the data easier for the scientist to interpret.

**Comment by ke-zhang-rd** [comment]
Closes #26

**Comment by danielballan** [comment]
Closed by #27
